spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: cheng1122
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 9090

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t6ah4EFn7phV1UV3Yey
    access-key-secret: DEJNtcIs5dpblzKhu0vq3CxiCl3jkD
    bucket-name: one-pic-bucket

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug